name 'bjc-ecommerce'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-ecommerce'
long_description 'Installs/Configures bjc-ecommerce'
source_url 'https://github.com/chef-cft/bjc'
issues_url 'https://github.com/chef-cft/bjc/issues'
version '0.1.17'
depends 'java', '= 1.42.0'
