name 'bjc-ecommerce'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-ecommerce'
long_description 'Installs/Configures bjc-ecommerce'
version '0.1.1'
depends 'java', '= 1.42.0'
