AllCops:
  Exclude:
    - test/**/*
    - spec/**/*
LineLength:
  Enabled: false
StringLiterals:
  Enabled: false
HashSyntax:
  Enabled: false
SpaceInsideParens:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
SpaceInsideHashLiteralBraces:
  Enabled: false
Encoding:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
AsciiComments:
  Enabled: false
NumericLiteralPrefix:
  Enabled: false
