name 'bjc_workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_workstation'
long_description 'Installs/Configures bjc_workstation'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '1.1.6'

depends 'workstation'
depends 'windows'
depends 'chocolatey'
depends 'wombat'
