name 'bjc_workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_workstation'
long_description 'Installs/Configures bjc_workstation'
version '0.1.22'

depends 'workstation'
depends 'windows'
depends 'chocolatey'
