source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat'
cookbook 'compliance', github: 'chef-cft/wombat', rel: 'cookbooks/compliance'
cookbook 'ccc', git: 'https://github.com/cheeseplus/ccc.git', branch: "updates"
cookbook 'audit', git: 'https://github.com/chef-cookbooks/audit', branch: "master"

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
