source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat', tag: 'v0.3.0'
cookbook 'compliance', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/compliance', tag: 'v0.3.0'
# This should be moved into chef-cft
cookbook 'ccc', git: 'https://github.com/cheeseplus/ccc.git', branch: "updates"
cookbook 'audit', git: 'https://github.com/chef-cookbooks/audit', branch: "master"

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
