name 'bjc_compliance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_compliance'
long_description 'Installs/Configures bjc_compliance'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '0.1.11'

depends 'compliance'
depends 'audit'
depends 'wombat'
