source 'https://supermarket.chef.io'

metadata

cookbook 'wombat',   github: 'chef-cft/wombat', rel: 'cookbooks/wombat'
cookbook 'compliance', github: 'chef-cft/wombat', rel: 'cookbooks/compliance'
cookbook 'ccc', git: 'https://github.com/cheeseplus/ccc.git', branch: "updates"

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end

