name 'bjc-compliance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-compliance'
long_description 'Installs/Configures bjc-compliance'
version '0.1.6'

depends 'compliance'
depends 'audit'
