name 'build-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
version '0.2.3'

depends 'sbp_packer'
depends 'delivery-truck'
depends 'delivery-sugar'
depends 'chef-sugar'
