name 'test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
source_url 'https://github.com/chef-cft/bjc'
issues_url 'https://github.com/chef-cft/bjc/issues'
license 'all_rights'
description 'Installs/Configures test'
long_description 'Installs/Configures test'
version '0.2.0'
