source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat'
cookbook 'chef_server', github: 'chef-cft/wombat', rel: 'cookbooks/chef_server'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
