source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat', tag: 'v0.3.4'
cookbook 'chef_server', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/chef_server', tag: 'v0.3.4'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
