name 'bjc_chef_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_chef_server'
long_description 'Installs/Configures bjc_chef_server'
version '0.1.9'

depends 'chef_server'
depends 'apt'
depends 'build-essential'
