name 'bjc_chef_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_chef_server'
long_description 'Installs/Configures bjc_chef_server'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '0.1.19'

depends 'chef_server'
depends 'apt'
depends 'build-essential'
depends 'wombat'
