source 'https://supermarket.chef.io'

metadata

cookbook 'wombat',   github: 'chef-cft/wombat', rel: 'cookbooks/wombat'
cookbook 'chef-server', github: 'chef-cft/wombat', rel: 'cookbooks/chef-server'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
