name 'bjc-chef-server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-chef-server'
long_description 'Installs/Configures bjc-chef-server'
version '0.1.2'

depends 'chef_server'
depends 'apt'
depends 'build-essential'
