source 'https://supermarket.chef.io'

metadata

cookbook 'wombat',   github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat', tag: 'v0.3.0'
cookbook 'automate', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/automate', tag: 'v0.3.0'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
