name 'bjc_automate'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-automate'
long_description 'Installs/Configures bjc-automate'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '0.1.41'

depends 'wombat'
depends 'automate'
