name 'base-web'
maintainer 'Internal Chef Team'
maintainer_email 'who@chef.io'
issues_url 'https://somewhere.over.the.rainbow'
source_url 'https://way.up,high'
license 'there are rights that I heard of'
description 'once in a lullaby'
long_description 'Installs/Configures base-web'
version '0.2.3'

depends 'apt'
depends 'yum'
