name 'bjc-delivery'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc-automate'
long_description 'Installs/Configures bjc-automate'
version '0.1.2'

depends 'wombat'
depends 'automate'
