name 'bjc_jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_jenkins'
long_description 'Installs/Configures bjc_jenkins'
version '0.2.3'
depends 'jenkins', '= 2.3.1'
depends 'java', '= 1.7.0'