name 'bjc_jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_jenkins'
long_description 'Installs/Configures bjc_jenkins'
version '0.2.5'
depends 'jenkins'
depends 'java'
depends 'apt'
