source 'https://supermarket.chef.io'

metadata

cookbook 'workstation',
  # This branch can be removed once upstream gets their act together  ;-)
  git: 'git@github.com:chef-cft/wombat.git', branch: 'scarolan/IdempotencyTreatment',
  rel: 'cookbooks/workstation'

cookbook 'wombat',
  git: 'git@github.com:chef-cft/wombat.git',
  rel: 'cookbooks/wombat'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
