source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat', tag: 'v0.3.4'
cookbook 'build_node', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/build_node', tag: 'v0.3.4'
# This probably ought to be moved into chef-cft
cookbook 'delivery_build', git: "https://github.com/andrewelizondo/delivery_build"
cookbook 'delivery-base', git: "https://github.com/chef-cookbooks/delivery-base"

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
