name 'bjc_build_node'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_build_node'
long_description 'Installs/Configures bjc_build_node'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '0.1.12'

depends 'build_node'
depends 'wombat'
