source 'https://supermarket.chef.io'

metadata

cookbook 'wombat', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/wombat'
cookbook 'infranodes', github: 'chef-cft/wombat', rel: 'generator_files/cookbooks/infranodes'

group :integration do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
