name 'bjc_infranodes'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bjc_infranodes'
long_description 'Installs/Configures bjc_infranodes'
issues_url 'https://waffle.io/chef-cft/bjc'
source_url 'https://github.com/chef-cft/bjc'
version '0.1.26'

depends 'infranodes'
depends 'wombat'
